### PR TITLE
Fix msi plessey

### PR DESCRIPTION
**Pull request by 4BooM04**

### CODE REVIEW

**Review by MrDyro — APPROVED** [review]

**Comment by MrDyro** [comment]
Waiting for testing

**Review by MrDyro — APPROVED** [review]

**Comment by Nikituh** [comment]
I don't understand why `msi plessey` was added to the list there. Can't all references of it just be removed?

**Comment by MrDyro** [comment]
> I don't understand why `msi plessey` was added to the list there. Can't all references of it just be removed?

@4BooM04 can you explain why?

**Comment by 4BooM04** [comment]
> > I don't understand why `msi plessey` was added to the list there. Can't all references of it just be removed?
> 
> @4BooM04 can you explain why?

I can. When we was working on new ask update we saw that it is in the list in native sdk. Layer as discussed with Eddy and Volkmar we made it hidden in common list for flutter barcodes, but after that native sdk got a task to delete is, so I guess next release we will just remove it from flutter completely

**Pull request closed without merging**
